name: CI

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: '14'
          registry-url: 'https://registry.npmjs.org'
      - run: npm i -g pnpm
      - run: pnpm i
      - run: pnpm lint
      - run: pnpm format
