name: Deploy

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: 8
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'pnpm'
      - run: pnpm i
      - run: pnpm type-check
      - run: pnpm build
      - run: pnpm test
      - name: Deploy to DigitalOcean droplet
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DO_SSH_HOST }}
          username: ${{ secrets.DO_SSH_USERNAME }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /home/nodejs/tauri-github-bot
            git pull
            rm .env;
            echo 'APP_ID=${{ secrets.APP_ID }}' >> .env
            echo 'WEBHOOK_SECRET=${{ secrets.WEBHOOK_SECRET }}' >> .env
            echo 'TAURI_BOT_ACC_TOKEN=${{ secrets.TAURI_BOT_ACC_TOKEN }}' >> .env
            echo 'PORT=9000' >> .env
            echo '${{ secrets.PRIVATE_KEY }}' > tauri-github-bot.private-key.pem
            ls -lah
            pnpm i
            pnpm build
            sudo -u nodejs pm2 restart 'tauri-github-bot'
