name: Depoly

on:
  push:
    branches:
      - dev

jobs:
  depoly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: cloudflare/wrangler-action@1.1.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_KEY }}
